name: {{ cookiecutter.project_slug }}
channels:
 - conda-forge
dependencies:
 - findspark=1.0.0
 - jupyter=1.0.0
 - python=3.6.1
 - pandas=0.22.0
 - scipy=1.0.0
 - seaborn=0.8.1
 - statsmodels=0.8.0
 - numpy=1.14.2
 - pip:
    - bumpversion==0.5.3
    - python-dotenv==0.6.4
