name: {{ cookiecutter.project_slug }}
channels:
 - conda-forge
dependencies:
 - findspark=1.0.0
 - ipykernel=4.6.1
 - jupyter_core=4.3.0
 - python=3.6.1
 - pandas=0.20.1
 - scipy=0.19.0
 - seaborn=0.7.1
 - statsmodels=0.8.0
 - numpy=1.12.1
 - pip:
    - bumpversion==0.5.3
    - python-dotenv==0.6.4
